env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    rclone_config: "ENCRYPTED[756a035b1056843cfac9b5b4dc0ab3ad017df8e89854c1fc7807dc9ffa3774ce01b18e396eed1e8912adb93d08bdb791]"

task:
    name: Build
    timeout_in: 120m
    container:
      image: fr3akyphantom/droid-builder:latest
      cpu: 4
      memory: 16G
    download_ccache_background_script:
      - apt-get install -y aria2
      - ./download_ccache
    sync_script:
      - ./sync
    monitor_background_script:
      - ./monitor
    build_script:
      - ./build
    upload_ccache_script:
      - ./upload_ccache
