env: # Environt variable to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone repo
    rclone_config: "ENCRYPTED[2ae235a6c94975acd8fa413196071833544a9ec981d66843a6176f5093582e8529a2d44c6d41d70a1a8e671c4474ae86]"

task:
    name: Buildtest
    timeout_in: 120m
    container:
      image: apon77/aosp:latest
      cpu: 8
      memory: 24G
    download_ccache_background_script:
      - bash download_ccache
    sync_script:
      - bash sync
    monitor_background_script:
      - bash monitor
    build_script:
      - bash build
    upload_ccache_script:
      - bash upload_ccache

