#!/bin/bash
cd /tmp/rom 

# Normal build steps
. build/envsetup.sh
lunch twrp_mojito-eng
export SKIP_API_CHECKS=true
export SKIP_ABI_CHECKS=true
#export TW_THEME=portrait_hdpi
export ALLOW_MISSING_DEPENDENCIES=true
#export SELINUX_IGNORE_NEVERALLOWS=true
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
export LC_ALL=C
ccache -M 20G 
ccache -o compression=true
ccache -z

#make api-stubs-docs || echo no problem, we need ccache
#make system-api-stubs-docs || echo no problem we need ccache
#make test-api-stubs-docs || echo no problem, we need ccache
#make aex -j10 &
#sleep 85m
#kill %1
#ccache -s

up(){
	curl --upload-file $1 https://transfer.sh/$(basename $1); echo
	# 14 days, 10 GB limit
}

tg(){
	bot_api=1710768515:AAEpUOXucT8Regv0NhAB7eMwHZgJ39xgv-M
	your_telegram_id=$1
	msg=$2
	curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=$msg&chat_id=${your_telegram_id}"
}

id=544521199
#make api-stubs-docs || echo no problem
#make system-api-stubs-docs || echo no problem
#make test-api-stubs-docs || echo no problem
#make sepolicy
#make bootimage
#make init
repo sync -j4

mka bootimage -j$(nproc -all)

up out/target/product/mojito/*.zip && up out/target/product/mojito/*.img
ccache -s
